### ISSUE TITLE
shlex call in mecab breaks library with downloaded dictionaries on windows

### ISSUE THREAD

**Issue by mlidbom** [KoichiYasuoka/UniDic2UD#2]
A call to `shlex.split(args)` within mecab strips \\\\ characters from paths unless the paths are enclosed by " characters.

line 224 in unidic2ud.py does not do this: 
`self.mecab=Tagger("-r "+r+" -d "+d).parse`

thus the library does not work with downloaded dictionaries on windows. 
this modified line fixes the problem.

`self.mecab=Tagger(f"""-r "{r}" -d "{d}" """).parse`

mecab itself does enclose paths in this way within it's own code, so I find it highly unlikely that this modification will break anything on other platforms.

All the best :)

**Comment by mlidbom** [comment]
I just realized that the same problem exists just a few lines down as well on line 231
I cannot test this code since I'm not using unidic-lite, but this line should work:

`self.mecab = Tagger(f"""-r "{r}" -d "{unidic_lite.DICDIR}" """).parse`

Those are famous last words though!

**Comment by KoichiYasuoka** [comment]
Yes @mlidbom it does occur on Windows environment. However, as I mentioned in #1, I cannot support Windows environment but support Cygwin.

**Comment by mlidbom** [comment]
Not officially supporting windows is entirely reasonable. But, in my opinion, there is a difference between not officially supporting it and not making a very minor change that makes everything work on windows when someone has already done all the work of debugging the problem for you. It took me hours of frustration to figure this out....

Please note that the code in #1 uses single quotes. What mecab uses internally is double quotes.

I modeled the quoting on precisely how mecab itself quotes those arguments when it passes them to itself in the method that croaks on how this project's code passes parameters without the quotes. So I really find it exceedingly hard to believe that adding those quotes would break your project or constitute a problem for you.

this is the mecab internal code that does the same thing: 
`args = '-r "{}" -d "{}" '.format(mecabrc, unidicdir) + args`


I would really appreciate it if you could take the time necessary to pop those lines in there and run your tests to see that yes, it does work. I'm not asking for you to officially support windows. I'm only asking for a tiny code change that, in my experience, results in everything working like a charm on windows.

FYI It's not feasible for me to use cygwin. I'm building an Anki plugin for studying Japanese...

**Comment by KoichiYasuoka** [comment]
Sorry @mlidbom but your modification causes an error on Cygwin with [mecab-cygwin](https://pypi.org/project/mecab-cygwin/).

```
Traceback (most recent call last):
  File "/usr/bin/unidic2ud", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/unidic2ud/cli.py", line 43, in main
    nlp=unidic2ud.load(d)
  File "/usr/lib/python3.7/site-packages/unidic2ud/unidic2ud.py", line 471, in load
    return UniDic2UD(UniDic,UDPipe)
  File "/usr/lib/python3.7/site-packages/unidic2ud/unidic2ud.py", line 224, in __init__
    self.mecab=Tagger(f"""-r "{r}" -d "{d}" """).parse
  File "/usr/lib/python3.7/site-packages/MeCab/__init__.py", line 99, in __init__
    super(Tagger, self).__init__(*args)
RuntimeError
```

**Comment by mlidbom** [comment]
Thank you very much for trying it out. It is much appreciated. I apologize for wasting your time :(
I guess I will either have to modify the library code locally or use something else. Too bad.

Thanks again! Have a great day :)

**Comment by KoichiYasuoka** [comment]
UniDic2UD [version 3.0.2](https://pypi.org/project/unidic2ud/3.0.2/) now utilizes

```
        self.mecab=Tagger("-r "+r.replace("\\","\\\\")+" -d "+d.replace("\\","\\\\")).parse
```

and it works well on both Cygwin and Linux.

**Comment by mlidbom** [comment]
And it works on windows too :)

Not only did you fix a bug for an environment you do not really want to support, but you made an instant new release of the library. That's going above and beyond. 

本当にありがとうございました
